```{r}
library(tidyverse)
library(tidymodels)
library(probably)
library(themis)
library(feather)
library(magrittr)
library(skimr)
library(vip)
library(lubridate)
library(xgboost)
library(modeltime)
library(timetk)
library(earth)
```


```{r}
ts_deaths <- read_feather("data/deaths_zip3.feather") 
```

```{r}
sample_n_groups = function(grouped_df, size, replace = FALSE, weight=NULL) {
  grp_var <- grouped_df %>% 
    groups %>%
    unlist %>% 
    as.character
  random_grp <- grouped_df %>% 
    summarise() %>% 
    sample_n(size, replace, weight) %>% 
    mutate(unique_id = 1:NROW(.))
  grouped_df %>% 
    right_join(random_grp, by=grp_var) %>% 
    group_by_(grp_var) 
}
```

```{r}
set.seed(42)
data<-ts_deaths %>% group_by(zip3) %>% sample_n_groups(10) %>% 
   select(zip3, date, deaths) %>%
    set_names(c("ID", "date", "value"))
```
```{r}
data %>%
  group_by(ID) %>%
  plot_time_series(
    .date_var    = date, 
    .value       = value,
    .facet_ncol  = 3,
    .interactive = FALSE
  )
  
```
```{r}
splits <- data %>% time_series_split(assess = "3 months", cumulative = TRUE)
splits
```
```{r}
rec_obj <- recipe(value ~ ., training(splits)) %>%
    step_mutate(ID = droplevels(ID)) %>%
    step_timeseries_signature(date) %>%
    step_rm(date) %>%
    step_zv(all_predictors()) %>%
    step_dummy(all_nominal_predictors(), one_hot = TRUE)

summary(prep(rec_obj))
```

```{r}
# Workflow
wflw_xgb <- workflow() %>%
    add_model(
        boost_tree() %>% set_engine("xgboost")
    ) %>%
    add_recipe(rec_obj) %>%
    fit(training(splits))

wflw_xgb
```
```{r}
model_tbl <- modeltime_table(
    wflw_xgb
)

model_tbl
```

```{r}
calib_tbl <- model_tbl %>%
    modeltime_calibrate(quiet = FALSE,
      new_data = testing(splits), 
      id       = "ID"
    )

calib_tbl
```

