```{r}
library(tidyverse)
library(tidymodels)
library(feather)
library(tidymodels)


# Helper packages
library(readr)       # for importing data
library(vip)         # for variable importance plots
```

```{r}
# Load it instead of reprocessing
per <- read_feather("all_persons.feather")

# This is how much we expect to pay for each client in a year
exp <-
  per %>%
  group_by(client) %>%
  summarize(expected = sum(qx * FaceAmt), zip3 = first(zip3))

# This is how much we payed for each client in 2019
# This is terrible code, please fix
act_2019 <-
  per %>%
  filter(year == 2019) %>%
  group_by(client) %>%
  summarize(actual2019 = sum(FaceAmt))
act_2020 <-
  per %>%
  filter(year == 2020) %>%
  group_by(client) %>%
  summarize(actual2020 = sum(FaceAmt))
act_2021 <-
  per %>%
  filter(year == 2021) %>%
  group_by(client) %>%
  summarize(actual2021 = sum(FaceAmt))

# This is also terrible...
exp <-
  exp %>%
  left_join(act_2019) %>%
  left_join(act_2020) %>%
  left_join(act_2021) %>%
  replace_na(list(actual2019 = 0)) %>%
  replace_na(list(actual2020 = 0)) %>%
  replace_na(list(actual2021 = 0)) %>%
  mutate(AE2019 = actual2019 / expected) %>%
  mutate(AE2020 = actual2020 / expected) %>%
  mutate(AE2021 = actual2021 / ((7 / 12) * expected))

exp

other_data <-
  read_feather("data.feather") %>%
  select(zip3, POP, AREALAND, `Deaths involving COVID-19`, per_dem, `Social Vulnerability Index (SVI)`, `CVAC level of concern for vaccination rollout`) %>%
  rename(covid_deaths = `Deaths involving COVID-19`, svi = `Social Vulnerability Index (SVI)`, cvac = `CVAC level of concern for vaccination rollout`) %>%
  mutate(density = POP / AREALAND, AREALAND = NULL)

data <-
  exp %>%
  left_join(other_data) %>%
  mutate(zip3 = factor(zip3)) %>%
  mutate(Y = factor(AE2020 > 1.1))

glimpse(data)

data %>%
  count(Y)
```

```{r}
splits <- initial_split(data, strata = Y)
data_test <- testing(splits)
data_train <- training(splits)

data_test %>%
  count(Y)
data_train %>%
  count(Y)

set.seed(234)
val_set <- validation_split(data_train, 
                            strata = Y, 
                            prop = 0.80)
val_set

lr_mod <- 
  logistic_reg(penalty = tune(), mixture = 1) %>% 
  set_engine("glmnet")

client_rec <-
  recipe(Y ~ ., data = data_train) %>%
  update_role(client, new_role = "client ID") %>%
  update_role(actual2020, actual2021, AE2020, AE2021, new_role = "future") %>%
  step_rm(zip3) %>% 
  step_normalize(all_predictors())

summary(client_rec)
```

```{r}
lr_workflow <- 
  workflow() %>% 
  add_model(lr_mod) %>% 
  add_recipe(client_rec)

```

```{r}
lr_reg_grid <- tibble(penalty = 10^seq(-7, -4, length.out = 30))

lr_reg_grid %>% top_n(-5) # lowest penalty values
lr_reg_grid %>% top_n(5) 
```

```{r}
lr_res <- 
  lr_workflow %>% 
  tune_grid(val_set,
            grid = lr_reg_grid,
            control = control_grid(save_pred = TRUE),
            metrics = metric_set(roc_auc))

```

```{r}
lr_plot <- 
  lr_res %>% 
  collect_metrics() %>% 
  ggplot(aes(x = penalty, y = mean)) + 
  geom_point() + 
  geom_line() + 
  ylab("Area under the ROC Curve") +
  scale_x_log10(labels = scales::label_number())

lr_plot 

```
