```{r}
  library(tidyverse)
  library(feather)
  library(ggplot2)
  library(tidymodels)  
  library(readr)       # for importing data
  library(vip)
  library(lubridate)
```
Currently we use the threshold = 1.1
```{r}
  thres = 1.1
```

Read necessary other data(zip3)
```{r}
otherdata <- read_feather("data.feather")%>%
  mutate(density = POP / AREALAND, AREALAND = NULL)%>%
  select(-Unemployment_rate_2020,-'Deaths involving COVID-19', -'Deaths from All Causes',
         -HU,-AREA)
  
deaths <- read_feather("deaths_zip3.feather")%>%
    mutate(year = year(date), month = month(date), week = week(date))%>%
    select(-date)
```

Read simulate data(here i just use the first data set)
```{r}
  experience <- readRDS("simulation_data/experience_weekly_1.RDS")
  experience$death[experience$death==2] <- 1
  
  person <-readRDS("simulation_data/person_1.RDS")
```

Here we compute yearly AE:

Compute summary statistic for each client in 2019.
```{r}
clients_2019 <- experience %>%
  filter( year == c(2019))%>%
  left_join(person) %>%
  group_by(client, participant) %>%
  summarize(
    zip3 = first(zip3),
    FaceAmt = FaceAmt,
    qx= sum(qx),
    age = Age,
    sex = Sex,
    industry = industry,
    collar = collar,
    death = sum(death),
    expected = qx * FaceAmt,
    actual = death * FaceAmt,
  ) %>%
  ungroup()%>%
  group_by(client)%>%
  summarize(
    zip3 = first(zip3),
    size = n(),
    volume = sum(FaceAmt),
    avg_qx = mean(qx),
    avg_age = mean(age),
    per_male = sum(sex == "Male") / size,
    per_blue_collar = sum(collar == "blue") / size,
    expected = sum(expected),
    actual = sum(actual),
    ae = actual / expected,
    adverse = as.factor(ae > 1.1)
  )%>%
  relocate(adverse, ae, .after = zip3)
```

Compute summary statistic for each client in 2020.
```{r}
clients_2020 <- experience %>%
  filter( year == c(2020))%>%
  left_join(person) %>%
  group_by(client, participant) %>%
  summarize(
    zip3 = first(zip3),
    FaceAmt = FaceAmt,
    qx= sum(qx),
    age = Age,
    sex = Sex,
    industry = industry,
    collar = collar,
    death = sum(death),
    expected = qx * FaceAmt,
    actual = death * FaceAmt,
  ) %>%
  ungroup()%>%
  group_by(client)%>%
  summarize(
    zip3 = first(zip3),
    size = n(),
    volume = sum(FaceAmt),
    avg_qx = mean(qx),
    avg_age = mean(age),
    per_male = sum(sex == "Male") / size,
    per_blue_collar = sum(collar == "blue") / size,
    expected = sum(expected),
    actual = sum(actual),
    ae = actual / expected,
    adverse = as.factor(ae > 1.1)
  )%>%
  relocate(adverse, ae, .after = zip3)
```

Compute summary statistic for each client in 2021.
```{r}
clients_2021 <- experience %>%
  filter( year == c(2021))%>%
  left_join(person) %>%
  group_by(client, participant) %>%
  summarize(
    zip3 = first(zip3),
    FaceAmt = FaceAmt,
    qx= sum(qx),
    age = Age,
    sex = Sex,
    industry = industry,
    collar = collar,
    death = sum(death),
    expected = qx * FaceAmt,
    actual = death * FaceAmt,
  ) %>%
  ungroup()%>%
  group_by(client)%>%
  summarize(
    zip3 = first(zip3),
    size = n(),
    volume = sum(FaceAmt),
    avg_qx = mean(qx),
    avg_age = mean(age),
    per_male = sum(sex == "Male") / size,
    per_blue_collar = sum(collar == "blue") / size,
    expected = sum(expected),
    actual = sum(actual),
    ae = actual / expected,
    adverse = as.factor(ae > 1.1)
  )%>%
  relocate(adverse, ae, .after = zip3)
```

plot some graph to explain why we need new model to estimate mortailty

```{r}
ggplot(data = clients_2019, aes(x = volume/100000, y = ae))+
  geom_point()+
  geom_hline(aes(yintercept = thres), colour = 'red')
ggplot(data = clients_2020, aes(x = volume/100000, y = ae))+
  geom_point()+
  geom_hline(aes(yintercept = thres), colour = 'red')
ggplot(data = clients_2021, aes(x = volume/100000, y = ae))+
  geom_point()+
  geom_hline(aes(yintercept = thres), colour = 'red')
```
```{r}
ggplot(data = clients_2019, aes(x = adverse))+
  geom_bar()
ggplot(data = clients_2020, aes(x = adverse))+
  geom_bar()
ggplot(data = clients_2021, aes(x = adverse))+
  geom_bar()
```
